### ISSUE TITLE
安装apk之后，手机界面都是花的，怎么解决这个问题。

### ISSUE THREAD

**Issue by wuxiaolianggit** [chentyjpm/MobileNetSSD_Demo_AndoridNCNN#2]
安装apk之后，手机界面都是花的，怎么解决这个问题。 @chentyjpm

**Comment by chentyjpm** [comment]
你这个是认真的吗？？？

**Comment by chentyjpm** [comment]
走camera2 的流程 自适应了分辨率 可能显示不正常了 @wuxiaolianggit  能说下你这个是那个手机
屏幕是什么分辨率么

**Comment by wuxiaolianggit** [comment]
我是认真的，确实整个屏幕是花的，看不清任何事物，我手机的分辨率是2160X1080

**Comment by wuxiaolianggit** [comment]
@chentyjpm

**Comment by chentyjpm** [comment]
@wuxiaolianggit 已经修复这个问题
